### ISSUE TITLE
Buildroot setup for Raspberry Pi 4B

### ISSUE THREAD

**Issue by ritikar97** [hgajapathy/final-project-hgajapathy#2]
DoD:

- [x]  Minimal Linux kernel image for Raspberry Pi 4B

Blockers: None

**Comment by hgajapathy** [comment]
1. Started buildroot project for Raspberry Pi 4B.
2. Learning on how to integrate BlueZ stack to custom Kernel Image.

**Comment by hgajapathy** [comment]
### Booted raspberry Pi 4B using Buildroot and successfully setup Wi-Fi, Bluetooth, and Python 3

See commit id: [9dcf9a6](https://github.com/cu-ecen-aeld/final-project-hgajapathy/commit/9dcf9a693bfd0b750b1c32e6256c02dc12601b51)


Wi-Fi

![Image](https://user-images.githubusercontent.com/86303418/232352271-5ca216f1-dfd5-4411-b9ae-7244f4f426c1.png)

Bluetooth

![Image](https://user-images.githubusercontent.com/86303418/232352329-03d1ab91-2a65-4d14-a6d7-0d728de20932.png)

Python 3

![Image](https://user-images.githubusercontent.com/86303418/232352389-2925f5b6-1457-4cc5-9fa4-f2825c6c5fd1.png)
