### ISSUE TITLE
Buildroot Setup for Raspberry Pi 3B+

### ISSUE THREAD

**Issue by hgajapathy** [hgajapathy/final-project-hgajapathy#3]
DoD:

- [x] Minimal Linux kernel image for Raspberry Pi 3B+
- [x] Flash the image onto the SD card. 
- [x] Edit the packages in the buildroot image to include the BME280 driver, before testing.

Blockers: None

**Comment by ritikar97** [comment]
The buildroot repo for this can be found [here](https://github.com/ritikar97/AESD_FinalProject_Buildroot), with commit ID [ae1f519](https://github.com/ritikar97/AESD_FinalProject_Buildroot/commit/ae1f519508dcae1f000e1451bcf54c66773a1c49).

The driver for BME280 was added and successfully loaded onto RPi 3B+. 



![Image](https://user-images.githubusercontent.com/112006837/233869957-17d66f42-c80a-4297-bb58-e181fcd760c6.jpg)
